### ISSUE TITLE
Internal Server Error when downloading FKB files

### ISSUE THREAD

**Issue by Kizlyk** [kartverket/Geonorge.NedlastingKlient#7]
When trying to download FKB data (for example: FKB-AR5 SOSI-format / SOSI-format, 0301, Oslo) using Nedlaster client I receive  internal server error response from API. 

This is the exact request that is being sent (credentials not included):

GET https://nedlasting.geonorge.no/api/download/file//166382b4-82d6-4ea9-a68e-6fd0c87bf788/41B7F899-9F38-436E-8577-E7999625C842 HTTP/1.1
Host: nedlasting.geonorge.no
User-Agent: GeonorgeNedlastingsklient/0.9.260.0
Authorization: Basic <credentials>

This is the response received:

HTTP/1.1 500 Internal Server Error
Server: nginx/1.20.1
Date: Wed, 21 Dec 2022 11:11:40 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 36
Connection: keep-alive
Cache-Control: no-cache
Pragma: no-cache
Expires: -1
Set-Cookie: _culture=no; path=/
Access-Control-Allow-Origin: https://kartkatalog.geonorge.no

{"Message":"An error has occurred."}

What might be the problem here?

**Comment by Kizlyk** [comment]
It worked with different credentials. So it's all good, although I would expect API to return a different error if there is something wrong with credentials

**Comment by larsingea** [comment]
Hi!
We looked into it yesterday, and thought it might be related to the credentials, but didn't manage to respond. Great that you figured it out yourself, and thank's for your feedback regarding improving the error message.
